/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademicAffairsRouteImport } from './routes/academic-affairs'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ExamActivityRouteImport } from './routes/exam-activity'
import { Route as IntegrityRouteImport } from './routes/integrity'
import { Route as ItemAnalysisRouteImport } from './routes/item-analysis'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as MyProgressRouteImport } from './routes/my-progress'
import { Route as ParticipationRouteImport } from './routes/participation'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as ProfessorRouteImport } from './routes/professor'
import { Route as ProgramDirectorRouteImport } from './routes/program-director'
import { Route as RealTimeRouteImport } from './routes/real-time'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicAffairsRoute = AcademicAffairsRouteImport.update({
  id: '/academic-affairs',
  path: '/academic-affairs',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamActivityRoute = ExamActivityRouteImport.update({
  id: '/exam-activity',
  path: '/exam-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrityRoute = IntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemAnalysisRoute = ItemAnalysisRouteImport.update({
  id: '/item-analysis',
  path: '/item-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProgressRoute = MyProgressRouteImport.update({
  id: '/my-progress',
  path: '/my-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipationRoute = ParticipationRouteImport.update({
  id: '/participation',
  path: '/participation',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorRoute = ProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramDirectorRoute = ProgramDirectorRouteImport.update({
  id: '/program-director',
  path: '/program-director',
  getParentRoute: () => rootRouteImport,
} as any)
const RealTimeRoute = RealTimeRouteImport.update({
  id: '/real-time',
  path: '/real-time',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic-affairs': typeof AcademicAffairsRoute
  '/courses': typeof CoursesRoute
  '/exam-activity': typeof ExamActivityRoute
  '/integrity': typeof IntegrityRoute
  '/item-analysis': typeof ItemAnalysisRoute
  '/management': typeof ManagementRoute
  '/my-progress': typeof MyProgressRoute
  '/participation': typeof ParticipationRoute
  '/performance': typeof PerformanceRoute
  '/professor': typeof ProfessorRoute
  '/program-director': typeof ProgramDirectorRoute
  '/real-time': typeof RealTimeRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic-affairs': typeof AcademicAffairsRoute
  '/courses': typeof CoursesRoute
  '/exam-activity': typeof ExamActivityRoute
  '/integrity': typeof IntegrityRoute
  '/item-analysis': typeof ItemAnalysisRoute
  '/management': typeof ManagementRoute
  '/my-progress': typeof MyProgressRoute
  '/participation': typeof ParticipationRoute
  '/performance': typeof PerformanceRoute
  '/professor': typeof ProfessorRoute
  '/program-director': typeof ProgramDirectorRoute
  '/real-time': typeof RealTimeRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/students': typeof StudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academic-affairs': typeof AcademicAffairsRoute
  '/courses': typeof CoursesRoute
  '/exam-activity': typeof ExamActivityRoute
  '/integrity': typeof IntegrityRoute
  '/item-analysis': typeof ItemAnalysisRoute
  '/management': typeof ManagementRoute
  '/my-progress': typeof MyProgressRoute
  '/participation': typeof ParticipationRoute
  '/performance': typeof PerformanceRoute
  '/professor': typeof ProfessorRoute
  '/program-director': typeof ProgramDirectorRoute
  '/real-time': typeof RealTimeRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic-affairs'
    | '/courses'
    | '/exam-activity'
    | '/integrity'
    | '/item-analysis'
    | '/management'
    | '/my-progress'
    | '/participation'
    | '/performance'
    | '/professor'
    | '/program-director'
    | '/real-time'
    | '/students/$studentId'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic-affairs'
    | '/courses'
    | '/exam-activity'
    | '/integrity'
    | '/item-analysis'
    | '/management'
    | '/my-progress'
    | '/participation'
    | '/performance'
    | '/professor'
    | '/program-director'
    | '/real-time'
    | '/students/$studentId'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/academic-affairs'
    | '/courses'
    | '/exam-activity'
    | '/integrity'
    | '/item-analysis'
    | '/management'
    | '/my-progress'
    | '/participation'
    | '/performance'
    | '/professor'
    | '/program-director'
    | '/real-time'
    | '/students/$studentId'
    | '/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicAffairsRoute: typeof AcademicAffairsRoute
  CoursesRoute: typeof CoursesRoute
  ExamActivityRoute: typeof ExamActivityRoute
  IntegrityRoute: typeof IntegrityRoute
  ItemAnalysisRoute: typeof ItemAnalysisRoute
  ManagementRoute: typeof ManagementRoute
  MyProgressRoute: typeof MyProgressRoute
  ParticipationRoute: typeof ParticipationRoute
  PerformanceRoute: typeof PerformanceRoute
  ProfessorRoute: typeof ProfessorRoute
  ProgramDirectorRoute: typeof ProgramDirectorRoute
  RealTimeRoute: typeof RealTimeRoute
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-affairs': {
      id: '/academic-affairs'
      path: '/academic-affairs'
      fullPath: '/academic-affairs'
      preLoaderRoute: typeof AcademicAffairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-activity': {
      id: '/exam-activity'
      path: '/exam-activity'
      fullPath: '/exam-activity'
      preLoaderRoute: typeof ExamActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrity': {
      id: '/integrity'
      path: '/integrity'
      fullPath: '/integrity'
      preLoaderRoute: typeof IntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item-analysis': {
      id: '/item-analysis'
      path: '/item-analysis'
      fullPath: '/item-analysis'
      preLoaderRoute: typeof ItemAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-progress': {
      id: '/my-progress'
      path: '/my-progress'
      fullPath: '/my-progress'
      preLoaderRoute: typeof MyProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participation': {
      id: '/participation'
      path: '/participation'
      fullPath: '/participation'
      preLoaderRoute: typeof ParticipationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor': {
      id: '/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof ProfessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-director': {
      id: '/program-director'
      path: '/program-director'
      fullPath: '/program-director'
      preLoaderRoute: typeof ProgramDirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-time': {
      id: '/real-time'
      path: '/real-time'
      fullPath: '/real-time'
      preLoaderRoute: typeof RealTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicAffairsRoute: AcademicAffairsRoute,
  CoursesRoute: CoursesRoute,
  ExamActivityRoute: ExamActivityRoute,
  IntegrityRoute: IntegrityRoute,
  ItemAnalysisRoute: ItemAnalysisRoute,
  ManagementRoute: ManagementRoute,
  MyProgressRoute: MyProgressRoute,
  ParticipationRoute: ParticipationRoute,
  PerformanceRoute: PerformanceRoute,
  ProfessorRoute: ProfessorRoute,
  ProgramDirectorRoute: ProgramDirectorRoute,
  RealTimeRoute: RealTimeRoute,
  StudentsStudentIdRoute: StudentsStudentIdRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
