/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoleRouteImport } from './routes/$role'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ExamActivityRouteImport } from './routes/exam-activity'
import { Route as IntegrityRouteImport } from './routes/integrity'
import { Route as ItemAnalysisRouteImport } from './routes/item-analysis'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as MyProgressRouteImport } from './routes/my-progress'
import { Route as ParticipationRouteImport } from './routes/participation'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as RealTimeRouteImport } from './routes/real-time'
import { Route as RoleIndexRouteImport } from './routes/$role.index'
import { Route as RoleCoursesRouteImport } from './routes/$role.courses'
import { Route as RoleExamActivityRouteImport } from './routes/$role.exam-activity'
import { Route as RoleIntegrityRouteImport } from './routes/$role.integrity'
import { Route as RoleItemAnalysisRouteImport } from './routes/$role.item-analysis'
import { Route as RoleParticipationRouteImport } from './routes/$role.participation'
import { Route as RolePerformanceRouteImport } from './routes/$role.performance'
import { Route as RoleRealTimeRouteImport } from './routes/$role.real-time'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'
import { Route as RoleStudentsIndexRouteImport } from './routes/$role.students.index'
import { Route as RoleStudentsStudentIdRouteImport } from './routes/$role.students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/$role',
  path: '/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamActivityRoute = ExamActivityRouteImport.update({
  id: '/exam-activity',
  path: '/exam-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrityRoute = IntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemAnalysisRoute = ItemAnalysisRouteImport.update({
  id: '/item-analysis',
  path: '/item-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProgressRoute = MyProgressRouteImport.update({
  id: '/my-progress',
  path: '/my-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipationRoute = ParticipationRouteImport.update({
  id: '/participation',
  path: '/participation',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const RealTimeRoute = RealTimeRouteImport.update({
  id: '/real-time',
  path: '/real-time',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleIndexRoute = RoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoleRoute,
} as any)
const RoleCoursesRoute = RoleCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => RoleRoute,
} as any)
const RoleExamActivityRoute = RoleExamActivityRouteImport.update({
  id: '/exam-activity',
  path: '/exam-activity',
  getParentRoute: () => RoleRoute,
} as any)
const RoleIntegrityRoute = RoleIntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => RoleRoute,
} as any)
const RoleItemAnalysisRoute = RoleItemAnalysisRouteImport.update({
  id: '/item-analysis',
  path: '/item-analysis',
  getParentRoute: () => RoleRoute,
} as any)
const RoleParticipationRoute = RoleParticipationRouteImport.update({
  id: '/participation',
  path: '/participation',
  getParentRoute: () => RoleRoute,
} as any)
const RolePerformanceRoute = RolePerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => RoleRoute,
} as any)
const RoleRealTimeRoute = RoleRealTimeRouteImport.update({
  id: '/real-time',
  path: '/real-time',
  getParentRoute: () => RoleRoute,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleStudentsIndexRoute = RoleStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => RoleRoute,
} as any)
const RoleStudentsStudentIdRoute = RoleStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => RoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$role': typeof RoleRouteWithChildren
  '/courses': typeof CoursesRoute
  '/exam-activity': typeof ExamActivityRoute
  '/integrity': typeof IntegrityRoute
  '/item-analysis': typeof ItemAnalysisRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRoute
  '/my-progress': typeof MyProgressRoute
  '/participation': typeof ParticipationRoute
  '/performance': typeof PerformanceRoute
  '/real-time': typeof RealTimeRoute
  '/$role/courses': typeof RoleCoursesRoute
  '/$role/exam-activity': typeof RoleExamActivityRoute
  '/$role/integrity': typeof RoleIntegrityRoute
  '/$role/item-analysis': typeof RoleItemAnalysisRoute
  '/$role/participation': typeof RoleParticipationRoute
  '/$role/performance': typeof RolePerformanceRoute
  '/$role/real-time': typeof RoleRealTimeRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/$role/': typeof RoleIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/$role/students/$studentId': typeof RoleStudentsStudentIdRoute
  '/$role/students/': typeof RoleStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/exam-activity': typeof ExamActivityRoute
  '/integrity': typeof IntegrityRoute
  '/item-analysis': typeof ItemAnalysisRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRoute
  '/my-progress': typeof MyProgressRoute
  '/participation': typeof ParticipationRoute
  '/performance': typeof PerformanceRoute
  '/real-time': typeof RealTimeRoute
  '/$role/courses': typeof RoleCoursesRoute
  '/$role/exam-activity': typeof RoleExamActivityRoute
  '/$role/integrity': typeof RoleIntegrityRoute
  '/$role/item-analysis': typeof RoleItemAnalysisRoute
  '/$role/participation': typeof RoleParticipationRoute
  '/$role/performance': typeof RolePerformanceRoute
  '/$role/real-time': typeof RoleRealTimeRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/$role': typeof RoleIndexRoute
  '/students': typeof StudentsIndexRoute
  '/$role/students/$studentId': typeof RoleStudentsStudentIdRoute
  '/$role/students': typeof RoleStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$role': typeof RoleRouteWithChildren
  '/courses': typeof CoursesRoute
  '/exam-activity': typeof ExamActivityRoute
  '/integrity': typeof IntegrityRoute
  '/item-analysis': typeof ItemAnalysisRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRoute
  '/my-progress': typeof MyProgressRoute
  '/participation': typeof ParticipationRoute
  '/performance': typeof PerformanceRoute
  '/real-time': typeof RealTimeRoute
  '/$role/courses': typeof RoleCoursesRoute
  '/$role/exam-activity': typeof RoleExamActivityRoute
  '/$role/integrity': typeof RoleIntegrityRoute
  '/$role/item-analysis': typeof RoleItemAnalysisRoute
  '/$role/participation': typeof RoleParticipationRoute
  '/$role/performance': typeof RolePerformanceRoute
  '/$role/real-time': typeof RoleRealTimeRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/$role/': typeof RoleIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/$role/students/$studentId': typeof RoleStudentsStudentIdRoute
  '/$role/students/': typeof RoleStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$role'
    | '/courses'
    | '/exam-activity'
    | '/integrity'
    | '/item-analysis'
    | '/login'
    | '/management'
    | '/my-progress'
    | '/participation'
    | '/performance'
    | '/real-time'
    | '/$role/courses'
    | '/$role/exam-activity'
    | '/$role/integrity'
    | '/$role/item-analysis'
    | '/$role/participation'
    | '/$role/performance'
    | '/$role/real-time'
    | '/students/$studentId'
    | '/$role/'
    | '/students/'
    | '/$role/students/$studentId'
    | '/$role/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/exam-activity'
    | '/integrity'
    | '/item-analysis'
    | '/login'
    | '/management'
    | '/my-progress'
    | '/participation'
    | '/performance'
    | '/real-time'
    | '/$role/courses'
    | '/$role/exam-activity'
    | '/$role/integrity'
    | '/$role/item-analysis'
    | '/$role/participation'
    | '/$role/performance'
    | '/$role/real-time'
    | '/students/$studentId'
    | '/$role'
    | '/students'
    | '/$role/students/$studentId'
    | '/$role/students'
  id:
    | '__root__'
    | '/'
    | '/$role'
    | '/courses'
    | '/exam-activity'
    | '/integrity'
    | '/item-analysis'
    | '/login'
    | '/management'
    | '/my-progress'
    | '/participation'
    | '/performance'
    | '/real-time'
    | '/$role/courses'
    | '/$role/exam-activity'
    | '/$role/integrity'
    | '/$role/item-analysis'
    | '/$role/participation'
    | '/$role/performance'
    | '/$role/real-time'
    | '/students/$studentId'
    | '/$role/'
    | '/students/'
    | '/$role/students/$studentId'
    | '/$role/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoleRoute: typeof RoleRouteWithChildren
  CoursesRoute: typeof CoursesRoute
  ExamActivityRoute: typeof ExamActivityRoute
  IntegrityRoute: typeof IntegrityRoute
  ItemAnalysisRoute: typeof ItemAnalysisRoute
  LoginRoute: typeof LoginRoute
  ManagementRoute: typeof ManagementRoute
  MyProgressRoute: typeof MyProgressRoute
  ParticipationRoute: typeof ParticipationRoute
  PerformanceRoute: typeof PerformanceRoute
  RealTimeRoute: typeof RealTimeRoute
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$role': {
      id: '/$role'
      path: '/$role'
      fullPath: '/$role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-activity': {
      id: '/exam-activity'
      path: '/exam-activity'
      fullPath: '/exam-activity'
      preLoaderRoute: typeof ExamActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrity': {
      id: '/integrity'
      path: '/integrity'
      fullPath: '/integrity'
      preLoaderRoute: typeof IntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item-analysis': {
      id: '/item-analysis'
      path: '/item-analysis'
      fullPath: '/item-analysis'
      preLoaderRoute: typeof ItemAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-progress': {
      id: '/my-progress'
      path: '/my-progress'
      fullPath: '/my-progress'
      preLoaderRoute: typeof MyProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participation': {
      id: '/participation'
      path: '/participation'
      fullPath: '/participation'
      preLoaderRoute: typeof ParticipationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-time': {
      id: '/real-time'
      path: '/real-time'
      fullPath: '/real-time'
      preLoaderRoute: typeof RealTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$role/': {
      id: '/$role/'
      path: '/'
      fullPath: '/$role/'
      preLoaderRoute: typeof RoleIndexRouteImport
      parentRoute: typeof RoleRoute
    }
    '/$role/courses': {
      id: '/$role/courses'
      path: '/courses'
      fullPath: '/$role/courses'
      preLoaderRoute: typeof RoleCoursesRouteImport
      parentRoute: typeof RoleRoute
    }
    '/$role/exam-activity': {
      id: '/$role/exam-activity'
      path: '/exam-activity'
      fullPath: '/$role/exam-activity'
      preLoaderRoute: typeof RoleExamActivityRouteImport
      parentRoute: typeof RoleRoute
    }
    '/$role/integrity': {
      id: '/$role/integrity'
      path: '/integrity'
      fullPath: '/$role/integrity'
      preLoaderRoute: typeof RoleIntegrityRouteImport
      parentRoute: typeof RoleRoute
    }
    '/$role/item-analysis': {
      id: '/$role/item-analysis'
      path: '/item-analysis'
      fullPath: '/$role/item-analysis'
      preLoaderRoute: typeof RoleItemAnalysisRouteImport
      parentRoute: typeof RoleRoute
    }
    '/$role/participation': {
      id: '/$role/participation'
      path: '/participation'
      fullPath: '/$role/participation'
      preLoaderRoute: typeof RoleParticipationRouteImport
      parentRoute: typeof RoleRoute
    }
    '/$role/performance': {
      id: '/$role/performance'
      path: '/performance'
      fullPath: '/$role/performance'
      preLoaderRoute: typeof RolePerformanceRouteImport
      parentRoute: typeof RoleRoute
    }
    '/$role/real-time': {
      id: '/$role/real-time'
      path: '/real-time'
      fullPath: '/$role/real-time'
      preLoaderRoute: typeof RoleRealTimeRouteImport
      parentRoute: typeof RoleRoute
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$role/students/': {
      id: '/$role/students/'
      path: '/students'
      fullPath: '/$role/students/'
      preLoaderRoute: typeof RoleStudentsIndexRouteImport
      parentRoute: typeof RoleRoute
    }
    '/$role/students/$studentId': {
      id: '/$role/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/$role/students/$studentId'
      preLoaderRoute: typeof RoleStudentsStudentIdRouteImport
      parentRoute: typeof RoleRoute
    }
  }
}

interface RoleRouteChildren {
  RoleCoursesRoute: typeof RoleCoursesRoute
  RoleExamActivityRoute: typeof RoleExamActivityRoute
  RoleIntegrityRoute: typeof RoleIntegrityRoute
  RoleItemAnalysisRoute: typeof RoleItemAnalysisRoute
  RoleParticipationRoute: typeof RoleParticipationRoute
  RolePerformanceRoute: typeof RolePerformanceRoute
  RoleRealTimeRoute: typeof RoleRealTimeRoute
  RoleIndexRoute: typeof RoleIndexRoute
  RoleStudentsStudentIdRoute: typeof RoleStudentsStudentIdRoute
  RoleStudentsIndexRoute: typeof RoleStudentsIndexRoute
}

const RoleRouteChildren: RoleRouteChildren = {
  RoleCoursesRoute: RoleCoursesRoute,
  RoleExamActivityRoute: RoleExamActivityRoute,
  RoleIntegrityRoute: RoleIntegrityRoute,
  RoleItemAnalysisRoute: RoleItemAnalysisRoute,
  RoleParticipationRoute: RoleParticipationRoute,
  RolePerformanceRoute: RolePerformanceRoute,
  RoleRealTimeRoute: RoleRealTimeRoute,
  RoleIndexRoute: RoleIndexRoute,
  RoleStudentsStudentIdRoute: RoleStudentsStudentIdRoute,
  RoleStudentsIndexRoute: RoleStudentsIndexRoute,
}

const RoleRouteWithChildren = RoleRoute._addFileChildren(RoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoleRoute: RoleRouteWithChildren,
  CoursesRoute: CoursesRoute,
  ExamActivityRoute: ExamActivityRoute,
  IntegrityRoute: IntegrityRoute,
  ItemAnalysisRoute: ItemAnalysisRoute,
  LoginRoute: LoginRoute,
  ManagementRoute: ManagementRoute,
  MyProgressRoute: MyProgressRoute,
  ParticipationRoute: ParticipationRoute,
  PerformanceRoute: PerformanceRoute,
  RealTimeRoute: RealTimeRoute,
  StudentsStudentIdRoute: StudentsStudentIdRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
